data_input_files:
  - '../data_upload/final_db1.json'
  - '../data_upload/final_db2.json'
  - '../data_upload/final_db3.json'
  - '../data_upload/final_db4.json'
output_path: '../data_upload/Enhanced_timeline.json'

