database:
  uri: "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.6"
  name: "timeline-project"
  version_1_collection: "generated_timelines"
  version_2_collection: "generated_hybrid_timelines"
  train_collection: "train_articles"
  test_collection: "test_articles"